import localFont from "next/font/local";
import "./globals.css";
import "./normalize.css"
import localFont from "next/font/local";
import Header from "./components/main/header";

const islamicFont = localFont({
  src: "./fonts/islamic.ttf",
  variable: "--font-islamic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={/*`${geistSans.variable} ${geistMono.variable}*/ `${islamicFont.variable}`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
